package com.jfast.pojo;

import java.io.Serializable;
import java.util.Date;

public class Dictionary extends DictionaryKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_name_cn
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private String dictNameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_name_en
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private String dictNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.sort
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.operator
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.create_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.update_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dictionary
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_name_cn
     *
     * @return the value of sys_dictionary.dict_name_cn
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public String getDictNameCn() {
        return dictNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_name_cn
     *
     * @param dictNameCn the value for sys_dictionary.dict_name_cn
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setDictNameCn(String dictNameCn) {
        this.dictNameCn = dictNameCn == null ? null : dictNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_name_en
     *
     * @return the value of sys_dictionary.dict_name_en
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public String getDictNameEn() {
        return dictNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_name_en
     *
     * @param dictNameEn the value for sys_dictionary.dict_name_en
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setDictNameEn(String dictNameEn) {
        this.dictNameEn = dictNameEn == null ? null : dictNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.sort
     *
     * @return the value of sys_dictionary.sort
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.sort
     *
     * @param sort the value for sys_dictionary.sort
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.operator
     *
     * @return the value of sys_dictionary.operator
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.operator
     *
     * @param operator the value for sys_dictionary.operator
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.create_time
     *
     * @return the value of sys_dictionary.create_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.create_time
     *
     * @param createTime the value for sys_dictionary.create_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.update_time
     *
     * @return the value of sys_dictionary.update_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.update_time
     *
     * @param updateTime the value for sys_dictionary.update_time
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictNameCn=").append(dictNameCn);
        sb.append(", dictNameEn=").append(dictNameEn);
        sb.append(", sort=").append(sort);
        sb.append(", operator=").append(operator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}