package com.jfast.pojo;

import java.io.Serializable;
import java.util.Date;

public class SysRole implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_id
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_name
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_type
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private String roleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_status
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private String roleStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.operator
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.create_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.update_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.description
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_id
	 * @return  the value of sys_role.role_id
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_id
	 * @param roleId  the value for sys_role.role_id
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_name
	 * @return  the value of sys_role.role_name
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_name
	 * @param roleName  the value for sys_role.role_name
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_type
	 * @return  the value of sys_role.role_type
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public String getRoleType() {
		return roleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_type
	 * @param roleType  the value for sys_role.role_type
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setRoleType(String roleType) {
		this.roleType = roleType == null ? null : roleType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_status
	 * @return  the value of sys_role.role_status
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public String getRoleStatus() {
		return roleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_status
	 * @param roleStatus  the value for sys_role.role_status
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setRoleStatus(String roleStatus) {
		this.roleStatus = roleStatus == null ? null : roleStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.operator
	 * @return  the value of sys_role.operator
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.operator
	 * @param operator  the value for sys_role.operator
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.create_time
	 * @return  the value of sys_role.create_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.create_time
	 * @param createTime  the value for sys_role.create_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.update_time
	 * @return  the value of sys_role.update_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.update_time
	 * @param updateTime  the value for sys_role.update_time
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.description
	 * @return  the value of sys_role.description
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.description
	 * @param description  the value for sys_role.description
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Tue Oct 29 17:08:29 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", roleId=").append(roleId);
		sb.append(", roleName=").append(roleName);
		sb.append(", roleType=").append(roleType);
		sb.append(", roleStatus=").append(roleStatus);
		sb.append(", operator=").append(operator);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", description=").append(description);
		sb.append("]");
		return sb.toString();
	}
}