package com.jfast.pojo;

import java.io.Serializable;
import java.util.Date;

public class SysRoleUser extends SysRoleUserKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_user.operator
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_user.create_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_user.update_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role_user
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_user.operator
	 * @return  the value of sys_role_user.operator
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_user.operator
	 * @param operator  the value for sys_role_user.operator
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_user.create_time
	 * @return  the value of sys_role_user.create_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_user.create_time
	 * @param createTime  the value for sys_role_user.create_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_user.update_time
	 * @return  the value of sys_role_user.update_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_user.update_time
	 * @param updateTime  the value for sys_role_user.update_time
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_user
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", operator=").append(operator);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append("]");
		return sb.toString();
	}
}