package com.jfast.pojo;

import java.io.Serializable;

public class SysRoleUserKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_user.role_id
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_user.uid
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role_user
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_user.role_id
	 * @return  the value of sys_role_user.role_id
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_user.role_id
	 * @param roleId  the value for sys_role_user.role_id
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_user.uid
	 * @return  the value of sys_role_user.uid
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_user.uid
	 * @param uid  the value for sys_role_user.uid
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_user
	 * @mbg.generated  Tue Oct 29 16:19:59 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", roleId=").append(roleId);
		sb.append(", uid=").append(uid);
		sb.append("]");
		return sb.toString();
	}
}