package com.jfast.pojo;

import java.io.Serializable;

public class DictionaryKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_type
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_code
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dictionary
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_type
     *
     * @return the value of sys_dictionary.dict_type
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_type
     *
     * @param dictType the value for sys_dictionary.dict_type
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_code
     *
     * @return the value of sys_dictionary.dict_code
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_code
     *
     * @param dictCode the value for sys_dictionary.dict_code
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbg.generated Mon Oct 21 11:38:02 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictType=").append(dictType);
        sb.append(", dictCode=").append(dictCode);
        sb.append("]");
        return sb.toString();
    }
}