package com.jfast.pojo;

import java.io.Serializable;
import java.util.Date;

public class LoginLog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.id
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.uid
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.phone
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.ip
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.location
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.version
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_log.time
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table login_log
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.id
	 * @return  the value of login_log.id
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.id
	 * @param id  the value for login_log.id
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.uid
	 * @return  the value of login_log.uid
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.uid
	 * @param uid  the value for login_log.uid
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.phone
	 * @return  the value of login_log.phone
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.phone
	 * @param phone  the value for login_log.phone
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.ip
	 * @return  the value of login_log.ip
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.ip
	 * @param ip  the value for login_log.ip
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.location
	 * @return  the value of login_log.location
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.location
	 * @param location  the value for login_log.location
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setLocation(String location) {
		this.location = location == null ? null : location.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.version
	 * @return  the value of login_log.version
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.version
	 * @param version  the value for login_log.version
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_log.time
	 * @return  the value of login_log.time
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_log.time
	 * @param time  the value for login_log.time
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_log
	 * @mbg.generated  Tue Nov 05 14:47:04 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", phone=").append(phone);
		sb.append(", ip=").append(ip);
		sb.append(", location=").append(location);
		sb.append(", version=").append(version);
		sb.append(", time=").append(time);
		sb.append("]");
		return sb.toString();
	}
}